version: '3.8'
services:
  postgres:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data
    networks:
      - postgres-network
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge